namespace ManufacturingAI.Setup;

internal static class EnvGenerator
{
    public static string Build(SetupState s)
    {
        var lines = new List<string>
        {
            "# ============================================================",
            "# BuildOwnRAG — generated by setup wizard",
            $"# {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC",
            "# ============================================================",
            "",
            "# ── PostgreSQL ────────────────────────────────────────────────",
            $"POSTGRES_DB={s.PostgresDb}",
            $"POSTGRES_USER={s.PostgresUser}",
            $"POSTGRES_PASSWORD={s.PostgresPassword}",
            $"POSTGRES_PORT={s.PostgresPort}",
            "",
            "# ── Port bindings ─────────────────────────────────────────────",
            "QDRANT_HTTP_PORT=6333",
            "QDRANT_GRPC_PORT=6334",
            "REDIS_PORT=6379",
            "APP_PORT=8080",
            "SETUP_PORT=8081",
            "ASPIRE_UI_PORT=18888",
            "ASPIRE_OTLP_PORT=18889",
            "",
            "# ── JWT ───────────────────────────────────────────────────────",
            $"JWT_SECRET={s.JwtSecret}",
            "JWT_ISSUER=BuildOwnRAG",
            "JWT_AUDIENCE=BuildOwnRAG",
            "",
            "# ── AES Encryption ────────────────────────────────────────────",
            $"ENCRYPTION_KEY={s.EncryptionKey}",
            $"ENCRYPTION_IV={s.EncryptionIv}",
            "",
            "# ── LLM Provider ──────────────────────────────────────────────",
            $"LLM__PROVIDER={s.LlmProvider}",
        };

        if (s.LlmProvider is "openai" or "azureopenai")
            lines.Add($"LLM__APIKEY={s.LlmApiKey}");

        lines.Add($"LLM__CHATMODEL={s.LlmChatModel}");

        if (s.LlmProvider == "azureopenai")
        {
            lines.Add($"LLM__AZUREENDPOINT={s.AzureEndpoint}");
            lines.Add($"LLM__DEPLOYMENTNAME={s.AzureDeployment}");
        }

        if (s.LlmProvider == "ollama")
        {
            lines.Add($"LLM__OLLAMABASEURL={s.OllamaBaseUrl}");
            lines.Add($"LLM__OLLAMACHATMODEL={s.OllamaChatModel}");
        }

        if (s.LlmProvider == "gemini")
        {
            lines.Add($"GEMINI_API_KEY={s.GeminiApiKey}");
            lines.Add($"GEMINI_CHAT_MODEL={s.GeminiChatModel}");
            lines.Add($"GEMINI_EMBEDDING_MODEL={s.GeminiEmbeddingModel}");
        }

        if (s.LlmProvider == "claude")
        {
            lines.Add($"CLAUDE_API_KEY={s.LlmApiKey}");
            lines.Add($"CLAUDE_CHAT_MODEL={s.LlmChatModel}");
        }

        lines.AddRange([
            "",
            "# ── Embedding ─────────────────────────────────────────────────",
            $"EMBEDDING__PROVIDER={s.EmbeddingProvider}",
            $"LLM__EMBEDDINGMODEL={s.EmbeddingModel}",
            $"LLM__EMBEDDINGDIMENSIONS={s.EmbeddingDimensions}",
        ]);

        if (s.EmbeddingProvider == "ollama")
        {
            lines.Add($"EMBEDDING__OLLAMAMODEL={s.OllamaEmbeddingModel}");
            lines.Add("EMBEDDING__OLLAMADIMENSIONS=768");
        }

        lines.AddRange([
            "",
            "# ── CORS ──────────────────────────────────────────────────────",
            "ALLOWED_ORIGINS=http://localhost:3000",
            "",
            "# ── Aspire Dashboard ──────────────────────────────────────────",
            "OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889",
            "OTEL_SERVICE_NAME=BuildOwnRAG.API",
            "",
            "# ── Setup ─────────────────────────────────────────────────────",
            "IS_SETUP_COMPLETED=true",
            "",
            "# ── License (optional) ────────────────────────────────────────",
            "LICENSE_SERVER_URL=",
            "LICENSE_KEY=",
        ]);

        return string.Join("\n", lines) + "\n";
    }

    public static async Task WriteAsync(SetupState s, string path = ".env")
    {
        var content = Build(s);
        await File.WriteAllTextAsync(path, content);
    }
}
